//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace garmentapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string nameprod { get; set; }
        public string season { get; set; }
        public string about { get; set; }
        public string color { get; set; }
        public int amount { get; set; }
        public int idUser { get; set; }
    
        public virtual users users { get; set; }
    }
}
